const testForm=document.querySelector('#testForm');const qaForm=document.querySelector('#qaForm');

const TEST_PLAN=[
  {participant:'P01',condition:'sin',task:'A · Dermatología · Dra. Paula Gómez · sede Norte · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P01',condition:'con',task:'B · Dermatología · Dra. Paula Gómez · sede Centro · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P02',condition:'con',task:'A · Dermatología · Dra. Paula Gómez · sede Norte · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P02',condition:'sin',task:'B · Dermatología · Dra. Paula Gómez · sede Centro · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P03',condition:'sin',task:'A · Dermatología · Dra. Paula Gómez · sede Norte · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P03',condition:'con',task:'B · Dermatología · Dra. Paula Gómez · sede Centro · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P04',condition:'con',task:'A · Dermatología · Dra. Paula Gómez · sede Norte · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P04',condition:'sin',task:'B · Dermatología · Dra. Paula Gómez · sede Centro · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P05',condition:'sin',task:'A · Dermatología · Dra. Paula Gómez · sede Norte · 27/08/2026 · llegar a Buscar horarios'},
  {participant:'P05',condition:'con',task:'B · Dermatología · Dra. Paula Gómez · sede Centro · 27/08/2026 · llegar a Buscar horarios'}
];
const PLAN_KEY='navegaclaro-test-plan-index-v1';
let testPlanIndex=Math.max(0,Math.min(TEST_PLAN.length,Number(localStorage.getItem(PLAN_KEY)||0)));
applyTestPlan();

function applyTestPlan(){const participant=document.querySelector('#participant');const condition=document.querySelector('#condition');const task=document.querySelector('#task');const status=document.querySelector('#testPlanStatus');const submit=testForm?.querySelector('button[type="submit"]');if(testPlanIndex>=TEST_PLAN.length){if(status)status.textContent='10 de 10 registros completados en este dispositivo. Verificá el dashboard antes de usar las métricas.';if(submit)submit.disabled=true;return;}const run=TEST_PLAN[testPlanIndex];if(participant)participant.value=run.participant;if(condition)condition.value=run.condition;if(task)task.value=run.task;if(status)status.textContent=`Registro ${testPlanIndex+1} de ${TEST_PLAN.length} · ${run.participant} · ${run.condition==='con'?'Con NavegaClaro':'Sin NavegaClaro'} · Tarea ${run.task.charAt(0)}`;if(submit)submit.disabled=false;}

testForm?.addEventListener('submit',async(event)=>{event.preventDefault();const status=document.querySelector('#testStatus');status.textContent='Guardando…';const token=document.querySelector('#adminToken').value.trim();const payload={participant:document.querySelector('#participant').value.trim(),condition:document.querySelector('#condition').value,task:document.querySelector('#task').value.trim(),success:document.querySelector('#success').value==='true',timeSeconds:Number(document.querySelector('#timeSeconds').value||0),errors:Number(document.querySelector('#errors').value||0),help:Number(document.querySelector('#help').value||0),ease:Number(document.querySelector('#ease').value||0),quote:document.querySelector('#quote').value.trim(),notes:document.querySelector('#notes').value.trim()};try{await send('test',payload,token);status.textContent='Prueba real guardada en Google Sheets.';testPlanIndex=Math.min(TEST_PLAN.length,testPlanIndex+1);localStorage.setItem(PLAN_KEY,String(testPlanIndex));document.querySelector('#timeSeconds').value='';document.querySelector('#errors').value='0';document.querySelector('#help').value='0';document.querySelector('#ease').value='3';document.querySelector('#quote').value='';document.querySelector('#notes').value='';applyTestPlan();}catch(error){status.textContent=error.message||'No se pudo guardar.';}});

qaForm?.addEventListener('submit',async(event)=>{event.preventDefault();const status=document.querySelector('#qaStatus');status.textContent='Guardando…';const token=document.querySelector('#qaAdminToken').value.trim();const payload={web:document.querySelector('#qaWeb').value.trim(),goal:document.querySelector('#qaGoal').value.trim(),result:document.querySelector('#qaResult').value,steps:Number(document.querySelector('#qaSteps').value||0),validTargets:document.querySelector('#qaTargets').value==='true',latencyMs:Number(document.querySelector('#qaLatency').value||0),notes:document.querySelector('#qaNotes').value.trim()};try{await send('qa',payload,token);status.textContent='QA guardado en Google Sheets.';document.querySelector('#qaNotes').value='';}catch(error){status.textContent=error.message||'No se pudo guardar.';}});

async function send(kind,payload,token){if(!token)throw new Error('Ingresá el token administrador.');const response=await fetch('/api/evidence',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token},body:JSON.stringify({kind,payload})});let data={};try{data=await response.json();}catch{}if(!response.ok||data.ok===false)throw new Error(data.error||`Error ${response.status}`);return data;}
