const RATE_WINDOW_MS=60_000;const RATE_MAX=30;const buckets=globalThis.__navegaClaroAvailabilityBuckets||new Map();globalThis.__navegaClaroAvailabilityBuckets=buckets;

export default async function handler(req,res){setCors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!allowRequest(req,res))return;const url=process.env.GOOGLE_SHEETS_WEBAPP_URL;const secret=process.env.GOOGLE_SHEETS_SHARED_SECRET;if(!url||!secret)return res.status(503).json({ok:false,configured:false,error:'La búsqueda de horarios todavía no está conectada a Google Sheets.'});let body;try{body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});}catch{return res.status(400).json({error:'JSON inválido'});}const query=normalize(body);const validation=validate(query);if(!validation.ok)return res.status(400).json({error:validation.error});try{const target=new URL(url);target.searchParams.set('action','availability');target.searchParams.set('secret',secret);if(query.specialty)target.searchParams.set('especialidad',query.specialty);if(query.professional)target.searchParams.set('profesional',query.professional);target.searchParams.set('sede',query.location);target.searchParams.set('fecha',query.date);const response=await fetch(target,{method:'GET',redirect:'follow',headers:{Accept:'application/json'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`Sheets ${response.status}`);const data=await response.json();if(data?.ok===false)throw new Error(data?.error||'Sheets rejected query');const slots=Array.isArray(data?.slots)?data.slots.map(sanitizeSlot).filter(Boolean).slice(0,12):[];return res.status(200).json({ok:true,configured:true,source:'google-sheets',slots});}catch(error){console.error('Availability lookup failed',error?.message||error);return res.status(502).json({ok:false,configured:true,error:'No se pudo consultar la disponibilidad en Google Sheets.'});}}

function normalize(body){return{specialty:text(body.specialty,120),professional:text(body.professional,120),location:text(body.location,120),date:text(body.date,10)}}
function validate(q){if(!q.specialty&&!q.professional)return{ok:false,error:'Escribí una especialidad o un profesional.'};if(!q.location)return{ok:false,error:'Elegí una sede.'};if(!/^\d{4}-\d{2}-\d{2}$/.test(q.date))return{ok:false,error:'Elegí una fecha válida.'};return{ok:true};}
function sanitizeSlot(value){const slotId=text(value?.slotId,100);const date=text(value?.date,10);const time=text(value?.time,8);if(!slotId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{1,2}:\d{2}$/.test(time))return null;return{slotId,specialty:text(value?.specialty,120),professional:text(value?.professional,120),location:text(value?.location,120),date,time,available:value?.available!==false};}
function text(value,max){return String(value||'').replace(/[\r\n\t]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);}
function allowRequest(req,res){const now=Date.now();const key=String(req.headers?.['x-forwarded-for']||req.headers?.['x-real-ip']||'unknown').split(',')[0].trim();const previous=(buckets.get(key)||[]).filter(time=>now-time<RATE_WINDOW_MS);if(previous.length>=RATE_MAX){res.setHeader('Retry-After','60');res.status(429).json({error:'Demasiadas búsquedas. Intentá nuevamente en un minuto.'});return false;}previous.push(now);buckets.set(key,previous);return true;}
function setCors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');}
